Repository EntryDSM/Entry-Admission, pull requests merged in 2025-08, with the labels that each got.

#85 fix (#84) : useNavigate() error fix
  apps/Admission-LTS/src/pages/Submitted.tsx
  libs/ui/src/BaseHeader.tsx
  libs/ui/vite.config.ts
  package.json
  yarn.lock
Labels: feat

#89 Feature/#86 guardian information
  apps/Admission-LTS/src/Router.tsx
  apps/Admission-LTS/src/layout/AppLayout.tsx
  apps/Admission-LTS/src/layout/ApplicationLayout.tsx
  apps/Admission-LTS/src/layout/RootLayout.tsx
  apps/Admission-LTS/src/pages/application/Fifth.tsx
  apps/Admission-LTS/src/pages/application/First.tsx
  apps/Admission-LTS/src/pages/application/Fourth.tsx
  apps/Admission-LTS/src/pages/application/Third.tsx
  apps/Admission-LTS/src/pages/application/index.ts
  apps/Admission-LTS/src/pages/ged/GedScore.tsx
  apps/Admission-LTS/src/pages/score/ScoreFirst.tsx
  apps/Admission-LTS/src/pages/score/ScoreFirstProspectiveGraduate.tsx
  apps/Admission-LTS/src/pages/score/ScoreFourth.tsx
  apps/Admission-LTS/src/pages/score/ScoreSecond.tsx
  apps/Admission-LTS/src/pages/score/ScoreSecondProspectiveGraduate.tsx
  apps/Admission-LTS/src/pages/score/ScoreThird.tsx
  apps/Admission-LTS/src/pages/score/ScoreThirdProspectiveGraduate.tsx
  libs/ui/src/AddressContent.tsx
  libs/ui/src/ApplicationNav.tsx
  libs/ui/src/FormElement.tsx
  libs/ui/src/ScorePageNav.tsx
  libs/ui/src/contexts/ApplicationDataContext.tsx
  libs/ui/src/index.ts
  libs/ui/src/utils/skipNextAutoSave.ts
  package.json
  yarn.lock
Labels: feat

#91 refactor (#90) : FormElement refactor
  apps/Admission-LTS/src/layout/ApplicationLayout.tsx
  apps/Admission-LTS/src/pages/application/Fifth.tsx
  apps/Admission-LTS/src/pages/application/Second.tsx
  apps/Admission-LTS/src/pages/application/Third.tsx
  libs/ui/src/ApplicationNav.tsx
  libs/ui/src/FormElement.tsx
  libs/ui/src/ImageContent.tsx
  libs/ui/src/utils/skipNextAutoSave.ts
Labels: feat

#93 feat (#92) : 봉사활동 페이지 수정 및 성별 추가
  apps/Admission-LTS/src/layout/ScoreLayout.tsx
  apps/Admission-LTS/src/pages/ActivityGraduate.tsx
  apps/Admission-LTS/src/pages/ActivityProspectiveGraduate.tsx
  apps/Admission-LTS/src/pages/application/Second.tsx
  libs/ui/src/contexts/ApplicationDataContext.tsx
Labels: feat

#96 fix (#95) : 유저 로그인 뷰 깨짐
  apps/entry-auth/src/pages/LoginPage.tsx
  libs/ui/src/Inputs.tsx
Labels: bug

#99 fix (#98) : admin, auth build err
  apps/entry-admin/src/assets/index.ts
  apps/entry-admin/src/components/FindApplicantInput.tsx
  apps/entry-auth/src/assets/Card/index.ts
Labels: bug

#103 fix (#102) : fix build error
  apps/entry-auth/src/components/index.ts
Labels: bug, feat

#104 fix (#102) : fix error
  apps/entry-auth/src/assets/Card/index.ts
Labels: bug

#113 Feature/#109 spinner
  apps/Admission-LTS/src/layout/AppLayout.tsx
  apps/Admission-LTS/src/pages/Landing.tsx
  apps/Admission-LTS/src/pages/Submitted.tsx
  apps/Admission-LTS/src/pages/application/First.tsx
  apps/Admission-LTS/src/pages/ged/GedScore.tsx
  libs/ui/src/ApplicationNav.tsx
  libs/ui/src/BaseHeader.tsx
  libs/ui/src/Button.tsx
  libs/ui/src/FormElement.tsx
  libs/ui/src/assets/icons/EntryLogo.tsx
  libs/ui/src/contexts/ApplicationDataContext.tsx
  libs/ui/src/contexts/index.ts
  libs/ui/src/contexts/pageValidation.ts
  package.json
  yarn.lock
Labels: feat

#118 feat (#114) : 전형 일정 수정 페이지와 정원 수정 페이지 추가
  apps/entry-admin/src/Router.tsx
  apps/entry-admin/src/components/DropDownSection.tsx
  apps/entry-admin/src/components/InputSection.tsx
  apps/entry-admin/src/components/index.ts
  apps/entry-admin/src/pages/AdmissionsQuota.tsx
  apps/entry-admin/src/pages/AdmissionsSchedule.tsx
  apps/entry-admin/src/pages/index.ts
  libs/ui/src/BaseHeader.tsx
Labels: feat

#120 feat (#119) : 졸업연월 타입 구분
  apps/Admission-LTS/src/pages/application/First.tsx
  libs/ui/src/contexts/pageValidation.ts
Labels: feat

#121 feat (#108) : pagination, 지원자 상세 조회
  apps/entry-admin/src/assets/cancel.svg
  apps/entry-admin/src/assets/index.ts
  apps/entry-admin/src/assets/left.svg
  apps/entry-admin/src/assets/right.svg
  apps/entry-admin/src/components/Applicant.tsx
  apps/entry-admin/src/components/ApplicantDetailModal.tsx
  apps/entry-admin/src/components/Pagination.tsx
  apps/entry-admin/src/components/index.ts
  apps/entry-admin/src/pages/ApplicantsList.tsx
Labels: feat

#126 feat (#125) : 지원자 조회 라우팅
  libs/ui/src/BaseHeader.tsx
Labels: feat

#129 feat (#128) : 404 페이지 추가 및 수정
  apps/Admission-LTS/src/Router.tsx
  apps/Admission-LTS/src/pages/Page404.tsx
  apps/Admission-LTS/src/pages/index.ts
  apps/entry-admin/src/Router.tsx
  apps/entry-admin/src/pages/Page404.tsx
  apps/entry-admin/src/pages/index.ts
  apps/entry-auth/src/Router.tsx
  apps/entry-auth/src/pages/Page404.tsx
  apps/entry-auth/src/pages/index.ts
  apps/entry-user/src/Router.tsx
  apps/entry-user/src/pages/Page404.tsx
  apps/entry-user/src/pages/index.ts
  libs/ui/src/index.ts
Labels: feat

#143 Feature/#132 api
  .gitignore
  apps/entry-admin/src/main.tsx
  libs/util-config/.babelrc
  libs/util-config/README.md
  libs/util-config/eslint.config.mjs
  libs/util-config/package.json
  libs/util-config/src/apis/feed/index.ts
  libs/util-config/src/apis/index.ts
  libs/util-config/src/apis/instance.tsx
  libs/util-config/src/apis/schedule/index.ts
  libs/util-config/src/apis/schedule/types.ts
  libs/util-config/src/apis/status/index.ts
  libs/util-config/src/apis/user/index.ts
  libs/util-config/src/env/index.ts
  libs/util-config/src/index.ts
  libs/util-config/tsconfig.json
  libs/util-config/tsconfig.lib.json
  libs/util-config/vite.config.ts
  tsconfig.json
Labels: feat

#146 fix (#145) : 지원자 조회 버튼 추가
  apps/entry-admin/src/App.tsx
  apps/entry-admin/src/components/Applicant.tsx
  apps/entry-admin/src/components/ApplicantExportBtn.tsx
  apps/entry-admin/src/components/index.ts
  apps/entry-admin/src/pages/ApplicantsList.tsx
Labels: bug
